//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datality.Tinker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blend : Chemical
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blend()
        {
            this.Pros = new HashSet<Pro>();
            this.Formulinos = new HashSet<Formulino>();
            this.SpecSet = new SpecSet();
        }
    
    
        public SpecSet SpecSet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pro> Pros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Formulino> Formulinos { get; set; }
        public virtual Safety Safety { get; set; }
    }
}
