//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datality.Tinker
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Chemical : Bass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chemical()
        {
            this.Toxicities = new HashSet<Toxicity>();
            this.Reggo = new Reggo();
            this.Transport = new Transport();
        }
    
        public string Name { get; set; }
    
        public Reggo Reggo { get; set; }
        public Transport Transport { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Toxicity> Toxicities { get; set; }
    }
}
