//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datality.Tinker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formulino : Bass
    {
        public string Low { get; set; }
        public string High { get; set; }
        public string Actual { get; set; }
        public string Range { get; set; }
    
        public virtual Raw Raw { get; set; }
        public virtual Blend Blend { get; set; }
    }
}
