//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datality.Tinker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pro : Bass
    {
        public string Name { get; set; }
        public string Class { get; set; }
        public string Description { get; set; }
        public string IssueDate { get; set; }
        public string RevisionDate { get; set; }
        public string Version { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Blend Blend { get; set; }
    }
}
