//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datality.Tinker
{
    using System;
    
    public partial class Sara
    {
        public int Rq { get; set; }
        public int Tpq { get; set; }
        public bool Sara313 { get; set; }
    }
}
