//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class defaultFields {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal defaultFields() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rockumentary.defaultFields", typeof(defaultFields).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Advice_on_safe_handling {
            get {
                return ResourceManager.GetString("Advice_on_safe_handling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Autoignition_temperature {
            get {
                return ResourceManager.GetString("Autoignition_temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Bioaccumulative_potential {
            get {
                return ResourceManager.GetString("Bioaccumulative_potential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Boiling_point {
            get {
                return ResourceManager.GetString("Boiling_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Carcinogenicity {
            get {
                return ResourceManager.GetString("Carcinogenicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Chemical_stability {
            get {
                return ResourceManager.GetString("Chemical_stability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Chronic {
            get {
                return ResourceManager.GetString("Chronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Comp1_RQ {
            get {
                return ResourceManager.GetString("Comp1_RQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Comp2_RQ {
            get {
                return ResourceManager.GetString("Comp2_RQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Comp3_RQ {
            get {
                return ResourceManager.GetString("Comp3_RQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Comp4_RQ {
            get {
                return ResourceManager.GetString("Comp4_RQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Comp5_RQ {
            get {
                return ResourceManager.GetString("Comp5_RQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Comp6_RQ {
            get {
                return ResourceManager.GetString("Comp6_RQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Conditions_to_avoid {
            get {
                return ResourceManager.GetString("Conditions_to_avoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Decomposition_temperature {
            get {
                return ResourceManager.GetString("Decomposition_temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Disposal {
            get {
                return ResourceManager.GetString("Disposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string DOT {
            get {
                return ResourceManager.GetString("DOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string DOT_label {
            get {
                return ResourceManager.GetString("DOT_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Embryotoxicity {
            get {
                return ResourceManager.GetString("Embryotoxicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Engineering_controls {
            get {
                return ResourceManager.GetString("Engineering_controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string EPA_number {
            get {
                return ResourceManager.GetString("EPA_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Evaporation_rate {
            get {
                return ResourceManager.GetString("Evaporation_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Explosive_limits {
            get {
                return ResourceManager.GetString("Explosive_limits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Eye_contact {
            get {
                return ResourceManager.GetString("Eye_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Eye_face_protection {
            get {
                return ResourceManager.GetString("Eye_face_protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string FA_eye_contact {
            get {
                return ResourceManager.GetString("FA_eye_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string FA_ingestion {
            get {
                return ResourceManager.GetString("FA_ingestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string FA_inhalation {
            get {
                return ResourceManager.GetString("FA_inhalation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string FA_skin_contact {
            get {
                return ResourceManager.GetString("FA_skin_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Flash_point {
            get {
                return ResourceManager.GetString("Flash_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Freezing_point {
            get {
                return ResourceManager.GetString("Freezing_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string General_hygiene_considerations {
            get {
                return ResourceManager.GetString("General_hygiene_considerations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Hazard_classification {
            get {
                return ResourceManager.GetString("Hazard_classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Hazard_classification1 {
            get {
                return ResourceManager.GetString("Hazard_classification1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Hazard_statement {
            get {
                return ResourceManager.GetString("Hazard_statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Hazardous_combustion_products {
            get {
                return ResourceManager.GetString("Hazardous_combustion_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No known non-thermal decomposition hazards.
        /// </summary>
        internal static string Hazardous_decomposition_products {
            get {
                return ResourceManager.GetString("Hazardous_decomposition_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Hazardous_polymerization {
            get {
                return ResourceManager.GetString("Hazardous_polymerization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Incompatibilities {
            get {
                return ResourceManager.GetString("Incompatibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Ingestion {
            get {
                return ResourceManager.GetString("Ingestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Inhalation {
            get {
                return ResourceManager.GetString("Inhalation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Large_spills {
            get {
                return ResourceManager.GetString("Large_spills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Likely_routes_of_exposure {
            get {
                return ResourceManager.GetString("Likely_routes_of_exposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Mobility {
            get {
                return ResourceManager.GetString("Mobility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Mutagenicity {
            get {
                return ResourceManager.GetString("Mutagenicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Note_to_HCP {
            get {
                return ResourceManager.GetString("Note_to_HCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Odor {
            get {
                return ResourceManager.GetString("Odor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Odor_threshold {
            get {
                return ResourceManager.GetString("Odor_threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Packing_group {
            get {
                return ResourceManager.GetString("Packing_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Partition_coefficient {
            get {
                return ResourceManager.GetString("Partition_coefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Persistence {
            get {
                return ResourceManager.GetString("Persistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Personal_precautions {
            get {
                return ResourceManager.GetString("Personal_precautions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string pH {
            get {
                return ResourceManager.GetString("pH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Pre_disposal {
            get {
                return ResourceManager.GetString("Pre_disposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Pre_prevention {
            get {
                return ResourceManager.GetString("Pre_prevention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Pre_response {
            get {
                return ResourceManager.GetString("Pre_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Pre_storage {
            get {
                return ResourceManager.GetString("Pre_storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Precautions_for_firefighters {
            get {
                return ResourceManager.GetString("Precautions_for_firefighters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string Primary_haz {
            get {
                return ResourceManager.GetString("Primary_haz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Product_class {
            get {
                return ResourceManager.GetString("Product_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Product_description {
            get {
                return ResourceManager.GetString("Product_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Product_name {
            get {
                return ResourceManager.GetString("Product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Product_RQ {
            get {
                return ResourceManager.GetString("Product_RQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Proper_shipping_name {
            get {
                return ResourceManager.GetString("Proper_shipping_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string RCRA_status {
            get {
                return ResourceManager.GetString("RCRA_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Reproductive_effects {
            get {
                return ResourceManager.GetString("Reproductive_effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Respiratory_protection {
            get {
                return ResourceManager.GetString("Respiratory_protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string Secondary_haz {
            get {
                return ResourceManager.GetString("Secondary_haz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Sensitization_to_product {
            get {
                return ResourceManager.GetString("Sensitization_to_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Signal_word {
            get {
                return ResourceManager.GetString("Signal_word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Skin_contact {
            get {
                return ResourceManager.GetString("Skin_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Skin_protection {
            get {
                return ResourceManager.GetString("Skin_protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Small_spills {
            get {
                return ResourceManager.GetString("Small_spills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Solubility {
            get {
                return ResourceManager.GetString("Solubility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Specific_gravity {
            get {
                return ResourceManager.GetString("Specific_gravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Specific_hazards {
            get {
                return ResourceManager.GetString("Specific_hazards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Storage_conditions {
            get {
                return ResourceManager.GetString("Storage_conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Suitable_extinguishing_media {
            get {
                return ResourceManager.GetString("Suitable_extinguishing_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Suitable_materials_of_construction {
            get {
                return ResourceManager.GetString("Suitable_materials_of_construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Supplier_address {
            get {
                return ResourceManager.GetString("Supplier_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Supplier_ec {
            get {
                return ResourceManager.GetString("Supplier_ec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Supplier_phone {
            get {
                return ResourceManager.GetString("Supplier_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Synergistic_products {
            get {
                return ResourceManager.GetString("Synergistic_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Teratogenicity {
            get {
                return ResourceManager.GetString("Teratogenicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string TSCA {
            get {
                return ResourceManager.GetString("TSCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string UN_number {
            get {
                return ResourceManager.GetString("UN_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Unsuitable_extinguishing_media {
            get {
                return ResourceManager.GetString("Unsuitable_extinguishing_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Unsuitable_materials_of_construction {
            get {
                return ResourceManager.GetString("Unsuitable_materials_of_construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Vapor_density {
            get {
                return ResourceManager.GetString("Vapor_density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Vapor_pressure {
            get {
                return ResourceManager.GetString("Vapor_pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string Viscosity {
            get {
                return ResourceManager.GetString("Viscosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string VOC_content {
            get {
                return ResourceManager.GetString("VOC_content", resourceCulture);
            }
        }
    }
}
