#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackcess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Datality")]
	public partial class LTSqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LTSqlDataContext() : 
				base(global::Hackcess.Properties.Settings.Default.DatalityConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LTSqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LTSqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LTSqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LTSqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Product_Log> Product_Logs
		{
			get
			{
				return this.GetTable<Product_Log>();
			}
		}
		
		public System.Data.Linq.Table<Branding> Brandings
		{
			get
			{
				return this.GetTable<Branding>();
			}
		}
		
		public System.Data.Linq.Table<Component> Components
		{
			get
			{
				return this.GetTable<Component>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Product Log]")]
	public partial class Product_Log
	{
		
		private int _PID;
		
		private string _Product_name;
		
		private string _OldUN;
		
		private string _Product_description;
		
		private string _Product_class;
		
		private System.Nullable<int> _Supplier_code;
		
		private bool _NSF;
		
		private bool _Kosher;
		
		private string _Comp1;
		
		private System.Nullable<float> _WeightRangeLow1;
		
		private System.Nullable<float> _WeightRangeHigh1;
		
		private string _WeightRange1;
		
		private string _Comp2;
		
		private System.Nullable<float> _WeightRangeLow2;
		
		private System.Nullable<float> _WeightRangeHigh2;
		
		private string _WeightRange2;
		
		private string _Comp3;
		
		private System.Nullable<float> _WeightRangeLow3;
		
		private System.Nullable<float> _WeightRangeHigh3;
		
		private string _WeightRange3;
		
		private string _Comp4;
		
		private System.Nullable<float> _WeightRangeLow4;
		
		private System.Nullable<float> _WeightRangeHigh4;
		
		private string _WeightRange4;
		
		private string _Comp5;
		
		private System.Nullable<float> _WeightRangeLow5;
		
		private System.Nullable<float> _WeightRangeHigh5;
		
		private string _WeightRange5;
		
		private string _Comp6;
		
		private System.Nullable<float> _WeightRangeLow6;
		
		private System.Nullable<float> _WeightRangeHigh6;
		
		private string _WeightRange6;
		
		private string _pH;
		
		private string _Specific_gravity;
		
		private string _Boiling_point;
		
		private string _Freezing_point;
		
		private string _Solubility;
		
		private string _Vapor_density;
		
		private string _Vapor_pressure;
		
		private string _Appearance;
		
		private string _Odor;
		
		private string _Flash_point;
		
		private string _Explosive_limits;
		
		private string _Autoignition_temperature;
		
		private string _EPA_number;
		
		private string _Decomposition_temperature;
		
		private string _Product_RQ;
		
		private string _Odor_threshold;
		
		private string _Evaporation_rate;
		
		private string _Partition_coefficient;
		
		private string _VOC_content;
		
		private string _Viscosity;
		
		private string _HMIS;
		
		private string _NFPA;
		
		private string _CAS1;
		
		private string _CAS2;
		
		private string _CAS3;
		
		private string _CAS4;
		
		private string _CAS5;
		
		private string _CAS6;
		
		private string _OSHA_PEL1;
		
		private string _OSHA_PEL2;
		
		private string _OSHA_PEL3;
		
		private string _OSHA_PEL4;
		
		private string _OSHA_PEL5;
		
		private string _OSHA_PEL6;
		
		private string _ACGIH_TLV1;
		
		private string _ACGIH_TLV2;
		
		private string _ACGIH_TLV3;
		
		private string _ACGIH_TLV4;
		
		private string _ACGIH_TLV5;
		
		private string _ACGIH_TLV6;
		
		private string _Health2;
		
		private string _Physical2;
		
		private string _Environmental2;
		
		private System.Nullable<System.DateTime> _goTime;
		
		private string _Clones;
		
		private System.Nullable<System.DateTime> _Issue_date;
		
		private System.Nullable<System.DateTime> _Revision_date;
		
		private System.Nullable<int> _Version;
		
		private string _Note;
		
		public Product_Log()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID", DbType="Int NOT NULL")]
		public int PID
		{
			get
			{
				return this._PID;
			}
			set
			{
				if ((this._PID != value))
				{
					this._PID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Product_name
		{
			get
			{
				return this._Product_name;
			}
			set
			{
				if ((this._Product_name != value))
				{
					this._Product_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OldUN", DbType="NVarChar(255)")]
		public string OldUN
		{
			get
			{
				return this._OldUN;
			}
			set
			{
				if ((this._OldUN != value))
				{
					this._OldUN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_description", DbType="NVarChar(MAX)")]
		public string Product_description
		{
			get
			{
				return this._Product_description;
			}
			set
			{
				if ((this._Product_description != value))
				{
					this._Product_description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_class", DbType="NVarChar(50)")]
		public string Product_class
		{
			get
			{
				return this._Product_class;
			}
			set
			{
				if ((this._Product_class != value))
				{
					this._Product_class = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_code", DbType="Int")]
		public System.Nullable<int> Supplier_code
		{
			get
			{
				return this._Supplier_code;
			}
			set
			{
				if ((this._Supplier_code != value))
				{
					this._Supplier_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NSF", DbType="Bit NOT NULL")]
		public bool NSF
		{
			get
			{
				return this._NSF;
			}
			set
			{
				if ((this._NSF != value))
				{
					this._NSF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kosher", DbType="Bit NOT NULL")]
		public bool Kosher
		{
			get
			{
				return this._Kosher;
			}
			set
			{
				if ((this._Kosher != value))
				{
					this._Kosher = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comp1", DbType="NVarChar(255)")]
		public string Comp1
		{
			get
			{
				return this._Comp1;
			}
			set
			{
				if ((this._Comp1 != value))
				{
					this._Comp1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightRangeLow1", DbType="Real")]
		public System.Nullable<float> WeightRangeLow1
		{
			get
			{
				return this._WeightRangeLow1;
			}
			set
			{
				if ((this._WeightRangeLow1 != value))
				{
					this._WeightRangeLow1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightRangeHigh1", DbType="Real")]
		public System.Nullable<float> WeightRangeHigh1
		{
			get
			{
				return this._WeightRangeHigh1;
			}
			set
			{
				if ((this._WeightRangeHigh1 != value))
				{
					this._WeightRangeHigh1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightRange1", DbType="NVarChar(255)")]
		public string WeightRange1
		{
			get
			{
				return this._WeightRange1;
			}
			set
			{
				if ((this._WeightRange1 != value))
				{
					this._WeightRange1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comp2", DbType="NVarChar(255)")]
		public string Comp2
		{
			get
			{
				return this._Comp2;
			}
			set
			{
				if ((this._Comp2 != value))
				{
					this._Comp2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightRangeLow2", DbType="Real")]
		public System.Nullable<float> WeightRangeLow2
		{
			get
			{
				return this._WeightRangeLow2;
			}
			set
			{
				if ((this._WeightRangeLow2 != value))
				{
					this._WeightRangeLow2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightRangeHigh2", DbType="Real")]
		public System.Nullable<float> WeightRangeHigh2
		{
			get
			{
				return this._WeightRangeHigh2;
			}
			set
			{
				if ((this._WeightRangeHigh2 != value))
				{
					this._WeightRangeHigh2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightRange2", DbType="NVarChar(255)")]
		public string WeightRange2
		{
			get
			{
				return this._WeightRange2;
			}
			set
			{
				if ((this._WeightRange2 != value))
				{
					this._WeightRange2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comp3", DbType="NVarChar(255)")]
		public string Comp3
		{
			get
			{
				return this._Comp3;
			}
			set
			{
				if ((this._Comp3 != value))
				{
					this._Comp3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightRangeLow3", DbType="Real")]
		public System.Nullable<float> WeightRangeLow3
		{
			get
			{
				return this._WeightRangeLow3;
			}
			set
			{
				if ((this._WeightRangeLow3 != value))
				{
					this._WeightRangeLow3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightRangeHigh3", DbType="Real")]
		public System.Nullable<float> WeightRangeHigh3
		{
			get
			{
				return this._WeightRangeHigh3;
			}
			set
			{
				if ((this._WeightRangeHigh3 != value))
				{
					this._WeightRangeHigh3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightRange3", DbType="NVarChar(255)")]
		public string WeightRange3
		{
			get
			{
				return this._WeightRange3;
			}
			set
			{
				if ((this._WeightRange3 != value))
				{
					this._WeightRange3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comp4", DbType="NVarChar(255)")]
		public string Comp4
		{
			get
			{
				return this._Comp4;
			}
			set
			{
				if ((this._Comp4 != value))
				{
					this._Comp4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightRangeLow4", DbType="Real")]
		public System.Nullable<float> WeightRangeLow4
		{
			get
			{
				return this._WeightRangeLow4;
			}
			set
			{
				if ((this._WeightRangeLow4 != value))
				{
					this._WeightRangeLow4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightRangeHigh4", DbType="Real")]
		public System.Nullable<float> WeightRangeHigh4
		{
			get
			{
				return this._WeightRangeHigh4;
			}
			set
			{
				if ((this._WeightRangeHigh4 != value))
				{
					this._WeightRangeHigh4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightRange4", DbType="NVarChar(255)")]
		public string WeightRange4
		{
			get
			{
				return this._WeightRange4;
			}
			set
			{
				if ((this._WeightRange4 != value))
				{
					this._WeightRange4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comp5", DbType="NVarChar(255)")]
		public string Comp5
		{
			get
			{
				return this._Comp5;
			}
			set
			{
				if ((this._Comp5 != value))
				{
					this._Comp5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightRangeLow5", DbType="Real")]
		public System.Nullable<float> WeightRangeLow5
		{
			get
			{
				return this._WeightRangeLow5;
			}
			set
			{
				if ((this._WeightRangeLow5 != value))
				{
					this._WeightRangeLow5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightRangeHigh5", DbType="Real")]
		public System.Nullable<float> WeightRangeHigh5
		{
			get
			{
				return this._WeightRangeHigh5;
			}
			set
			{
				if ((this._WeightRangeHigh5 != value))
				{
					this._WeightRangeHigh5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightRange5", DbType="NVarChar(255)")]
		public string WeightRange5
		{
			get
			{
				return this._WeightRange5;
			}
			set
			{
				if ((this._WeightRange5 != value))
				{
					this._WeightRange5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comp6", DbType="NVarChar(255)")]
		public string Comp6
		{
			get
			{
				return this._Comp6;
			}
			set
			{
				if ((this._Comp6 != value))
				{
					this._Comp6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightRangeLow6", DbType="Real")]
		public System.Nullable<float> WeightRangeLow6
		{
			get
			{
				return this._WeightRangeLow6;
			}
			set
			{
				if ((this._WeightRangeLow6 != value))
				{
					this._WeightRangeLow6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightRangeHigh6", DbType="Real")]
		public System.Nullable<float> WeightRangeHigh6
		{
			get
			{
				return this._WeightRangeHigh6;
			}
			set
			{
				if ((this._WeightRangeHigh6 != value))
				{
					this._WeightRangeHigh6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightRange6", DbType="NVarChar(255)")]
		public string WeightRange6
		{
			get
			{
				return this._WeightRange6;
			}
			set
			{
				if ((this._WeightRange6 != value))
				{
					this._WeightRange6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pH", DbType="NVarChar(255)")]
		public string pH
		{
			get
			{
				return this._pH;
			}
			set
			{
				if ((this._pH != value))
				{
					this._pH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Specific_gravity", DbType="NVarChar(255)")]
		public string Specific_gravity
		{
			get
			{
				return this._Specific_gravity;
			}
			set
			{
				if ((this._Specific_gravity != value))
				{
					this._Specific_gravity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boiling_point", DbType="NVarChar(255)")]
		public string Boiling_point
		{
			get
			{
				return this._Boiling_point;
			}
			set
			{
				if ((this._Boiling_point != value))
				{
					this._Boiling_point = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Freezing_point", DbType="NVarChar(255)")]
		public string Freezing_point
		{
			get
			{
				return this._Freezing_point;
			}
			set
			{
				if ((this._Freezing_point != value))
				{
					this._Freezing_point = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Solubility", DbType="NVarChar(255)")]
		public string Solubility
		{
			get
			{
				return this._Solubility;
			}
			set
			{
				if ((this._Solubility != value))
				{
					this._Solubility = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vapor_density", DbType="NVarChar(255)")]
		public string Vapor_density
		{
			get
			{
				return this._Vapor_density;
			}
			set
			{
				if ((this._Vapor_density != value))
				{
					this._Vapor_density = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vapor_pressure", DbType="NVarChar(255)")]
		public string Vapor_pressure
		{
			get
			{
				return this._Vapor_pressure;
			}
			set
			{
				if ((this._Vapor_pressure != value))
				{
					this._Vapor_pressure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Appearance", DbType="NVarChar(255)")]
		public string Appearance
		{
			get
			{
				return this._Appearance;
			}
			set
			{
				if ((this._Appearance != value))
				{
					this._Appearance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Odor", DbType="NVarChar(255)")]
		public string Odor
		{
			get
			{
				return this._Odor;
			}
			set
			{
				if ((this._Odor != value))
				{
					this._Odor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flash_point", DbType="NVarChar(255)")]
		public string Flash_point
		{
			get
			{
				return this._Flash_point;
			}
			set
			{
				if ((this._Flash_point != value))
				{
					this._Flash_point = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Explosive_limits", DbType="NVarChar(255)")]
		public string Explosive_limits
		{
			get
			{
				return this._Explosive_limits;
			}
			set
			{
				if ((this._Explosive_limits != value))
				{
					this._Explosive_limits = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Autoignition_temperature", DbType="NVarChar(255)")]
		public string Autoignition_temperature
		{
			get
			{
				return this._Autoignition_temperature;
			}
			set
			{
				if ((this._Autoignition_temperature != value))
				{
					this._Autoignition_temperature = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPA_number", DbType="NVarChar(255)")]
		public string EPA_number
		{
			get
			{
				return this._EPA_number;
			}
			set
			{
				if ((this._EPA_number != value))
				{
					this._EPA_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Decomposition_temperature", DbType="NVarChar(255)")]
		public string Decomposition_temperature
		{
			get
			{
				return this._Decomposition_temperature;
			}
			set
			{
				if ((this._Decomposition_temperature != value))
				{
					this._Decomposition_temperature = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_RQ", DbType="NVarChar(255)")]
		public string Product_RQ
		{
			get
			{
				return this._Product_RQ;
			}
			set
			{
				if ((this._Product_RQ != value))
				{
					this._Product_RQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Odor_threshold", DbType="NVarChar(255)")]
		public string Odor_threshold
		{
			get
			{
				return this._Odor_threshold;
			}
			set
			{
				if ((this._Odor_threshold != value))
				{
					this._Odor_threshold = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Evaporation_rate", DbType="NVarChar(255)")]
		public string Evaporation_rate
		{
			get
			{
				return this._Evaporation_rate;
			}
			set
			{
				if ((this._Evaporation_rate != value))
				{
					this._Evaporation_rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Partition_coefficient", DbType="NVarChar(255)")]
		public string Partition_coefficient
		{
			get
			{
				return this._Partition_coefficient;
			}
			set
			{
				if ((this._Partition_coefficient != value))
				{
					this._Partition_coefficient = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VOC_content", DbType="NVarChar(255)")]
		public string VOC_content
		{
			get
			{
				return this._VOC_content;
			}
			set
			{
				if ((this._VOC_content != value))
				{
					this._VOC_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Viscosity", DbType="NVarChar(255)")]
		public string Viscosity
		{
			get
			{
				return this._Viscosity;
			}
			set
			{
				if ((this._Viscosity != value))
				{
					this._Viscosity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HMIS", DbType="NVarChar(255)")]
		public string HMIS
		{
			get
			{
				return this._HMIS;
			}
			set
			{
				if ((this._HMIS != value))
				{
					this._HMIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NFPA", DbType="NVarChar(255)")]
		public string NFPA
		{
			get
			{
				return this._NFPA;
			}
			set
			{
				if ((this._NFPA != value))
				{
					this._NFPA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAS1", DbType="NVarChar(255)")]
		public string CAS1
		{
			get
			{
				return this._CAS1;
			}
			set
			{
				if ((this._CAS1 != value))
				{
					this._CAS1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAS2", DbType="NVarChar(255)")]
		public string CAS2
		{
			get
			{
				return this._CAS2;
			}
			set
			{
				if ((this._CAS2 != value))
				{
					this._CAS2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAS3", DbType="NVarChar(255)")]
		public string CAS3
		{
			get
			{
				return this._CAS3;
			}
			set
			{
				if ((this._CAS3 != value))
				{
					this._CAS3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAS4", DbType="NVarChar(255)")]
		public string CAS4
		{
			get
			{
				return this._CAS4;
			}
			set
			{
				if ((this._CAS4 != value))
				{
					this._CAS4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAS5", DbType="NVarChar(255)")]
		public string CAS5
		{
			get
			{
				return this._CAS5;
			}
			set
			{
				if ((this._CAS5 != value))
				{
					this._CAS5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAS6", DbType="NVarChar(255)")]
		public string CAS6
		{
			get
			{
				return this._CAS6;
			}
			set
			{
				if ((this._CAS6 != value))
				{
					this._CAS6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSHA_PEL1", DbType="NVarChar(255)")]
		public string OSHA_PEL1
		{
			get
			{
				return this._OSHA_PEL1;
			}
			set
			{
				if ((this._OSHA_PEL1 != value))
				{
					this._OSHA_PEL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSHA_PEL2", DbType="NVarChar(255)")]
		public string OSHA_PEL2
		{
			get
			{
				return this._OSHA_PEL2;
			}
			set
			{
				if ((this._OSHA_PEL2 != value))
				{
					this._OSHA_PEL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSHA_PEL3", DbType="NVarChar(255)")]
		public string OSHA_PEL3
		{
			get
			{
				return this._OSHA_PEL3;
			}
			set
			{
				if ((this._OSHA_PEL3 != value))
				{
					this._OSHA_PEL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSHA_PEL4", DbType="NVarChar(255)")]
		public string OSHA_PEL4
		{
			get
			{
				return this._OSHA_PEL4;
			}
			set
			{
				if ((this._OSHA_PEL4 != value))
				{
					this._OSHA_PEL4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSHA_PEL5", DbType="NVarChar(255)")]
		public string OSHA_PEL5
		{
			get
			{
				return this._OSHA_PEL5;
			}
			set
			{
				if ((this._OSHA_PEL5 != value))
				{
					this._OSHA_PEL5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSHA_PEL6", DbType="NVarChar(255)")]
		public string OSHA_PEL6
		{
			get
			{
				return this._OSHA_PEL6;
			}
			set
			{
				if ((this._OSHA_PEL6 != value))
				{
					this._OSHA_PEL6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACGIH_TLV1", DbType="NVarChar(255)")]
		public string ACGIH_TLV1
		{
			get
			{
				return this._ACGIH_TLV1;
			}
			set
			{
				if ((this._ACGIH_TLV1 != value))
				{
					this._ACGIH_TLV1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACGIH_TLV2", DbType="NVarChar(255)")]
		public string ACGIH_TLV2
		{
			get
			{
				return this._ACGIH_TLV2;
			}
			set
			{
				if ((this._ACGIH_TLV2 != value))
				{
					this._ACGIH_TLV2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACGIH_TLV3", DbType="NVarChar(255)")]
		public string ACGIH_TLV3
		{
			get
			{
				return this._ACGIH_TLV3;
			}
			set
			{
				if ((this._ACGIH_TLV3 != value))
				{
					this._ACGIH_TLV3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACGIH_TLV4", DbType="NVarChar(255)")]
		public string ACGIH_TLV4
		{
			get
			{
				return this._ACGIH_TLV4;
			}
			set
			{
				if ((this._ACGIH_TLV4 != value))
				{
					this._ACGIH_TLV4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACGIH_TLV5", DbType="NVarChar(255)")]
		public string ACGIH_TLV5
		{
			get
			{
				return this._ACGIH_TLV5;
			}
			set
			{
				if ((this._ACGIH_TLV5 != value))
				{
					this._ACGIH_TLV5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACGIH_TLV6", DbType="NVarChar(255)")]
		public string ACGIH_TLV6
		{
			get
			{
				return this._ACGIH_TLV6;
			}
			set
			{
				if ((this._ACGIH_TLV6 != value))
				{
					this._ACGIH_TLV6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Health2", DbType="NVarChar(255)")]
		public string Health2
		{
			get
			{
				return this._Health2;
			}
			set
			{
				if ((this._Health2 != value))
				{
					this._Health2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Physical2", DbType="NVarChar(255)")]
		public string Physical2
		{
			get
			{
				return this._Physical2;
			}
			set
			{
				if ((this._Physical2 != value))
				{
					this._Physical2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Environmental2", DbType="NVarChar(255)")]
		public string Environmental2
		{
			get
			{
				return this._Environmental2;
			}
			set
			{
				if ((this._Environmental2 != value))
				{
					this._Environmental2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_goTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> goTime
		{
			get
			{
				return this._goTime;
			}
			set
			{
				if ((this._goTime != value))
				{
					this._goTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clones", DbType="NVarChar(255)")]
		public string Clones
		{
			get
			{
				return this._Clones;
			}
			set
			{
				if ((this._Clones != value))
				{
					this._Clones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Issue_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Issue_date
		{
			get
			{
				return this._Issue_date;
			}
			set
			{
				if ((this._Issue_date != value))
				{
					this._Issue_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Revision_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Revision_date
		{
			get
			{
				return this._Revision_date;
			}
			set
			{
				if ((this._Revision_date != value))
				{
					this._Revision_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="Int")]
		public System.Nullable<int> Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this._Version = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(MAX)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this._Note = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Branding")]
	public partial class Branding
	{
		
		private int _CID;
		
		private string _Supplier_fullname;
		
		private string _Supplier;
		
		private string _Supplier_address_1;
		
		private string _Supplier_address_2;
		
		private string _Supplier_address_3;
		
		private string _Supplier_city;
		
		private string _Supplier_state;
		
		private string _Supplier_zip;
		
		private string _Supplier_phone;
		
		private string _Supplier_ec;
		
		private string _Website;
		
		private string _Heading1BG;
		
		private string _Heading1FG;
		
		private string _Heading1OL;
		
		public Branding()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CID", DbType="Int NOT NULL")]
		public int CID
		{
			get
			{
				return this._CID;
			}
			set
			{
				if ((this._CID != value))
				{
					this._CID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_fullname", DbType="NVarChar(255)")]
		public string Supplier_fullname
		{
			get
			{
				return this._Supplier_fullname;
			}
			set
			{
				if ((this._Supplier_fullname != value))
				{
					this._Supplier_fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Supplier
		{
			get
			{
				return this._Supplier;
			}
			set
			{
				if ((this._Supplier != value))
				{
					this._Supplier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_address_1", DbType="NVarChar(255)")]
		public string Supplier_address_1
		{
			get
			{
				return this._Supplier_address_1;
			}
			set
			{
				if ((this._Supplier_address_1 != value))
				{
					this._Supplier_address_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_address_2", DbType="NVarChar(255)")]
		public string Supplier_address_2
		{
			get
			{
				return this._Supplier_address_2;
			}
			set
			{
				if ((this._Supplier_address_2 != value))
				{
					this._Supplier_address_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_address_3", DbType="NVarChar(255)")]
		public string Supplier_address_3
		{
			get
			{
				return this._Supplier_address_3;
			}
			set
			{
				if ((this._Supplier_address_3 != value))
				{
					this._Supplier_address_3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_city", DbType="NVarChar(255)")]
		public string Supplier_city
		{
			get
			{
				return this._Supplier_city;
			}
			set
			{
				if ((this._Supplier_city != value))
				{
					this._Supplier_city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_state", DbType="NVarChar(2)")]
		public string Supplier_state
		{
			get
			{
				return this._Supplier_state;
			}
			set
			{
				if ((this._Supplier_state != value))
				{
					this._Supplier_state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_zip", DbType="NVarChar(10)")]
		public string Supplier_zip
		{
			get
			{
				return this._Supplier_zip;
			}
			set
			{
				if ((this._Supplier_zip != value))
				{
					this._Supplier_zip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_phone", DbType="NVarChar(255)")]
		public string Supplier_phone
		{
			get
			{
				return this._Supplier_phone;
			}
			set
			{
				if ((this._Supplier_phone != value))
				{
					this._Supplier_phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_ec", DbType="NVarChar(255)")]
		public string Supplier_ec
		{
			get
			{
				return this._Supplier_ec;
			}
			set
			{
				if ((this._Supplier_ec != value))
				{
					this._Supplier_ec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="NVarChar(255)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this._Website = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heading1BG", DbType="NVarChar(255)")]
		public string Heading1BG
		{
			get
			{
				return this._Heading1BG;
			}
			set
			{
				if ((this._Heading1BG != value))
				{
					this._Heading1BG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heading1FG", DbType="NVarChar(255)")]
		public string Heading1FG
		{
			get
			{
				return this._Heading1FG;
			}
			set
			{
				if ((this._Heading1FG != value))
				{
					this._Heading1FG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heading1OL", DbType="NVarChar(255)")]
		public string Heading1OL
		{
			get
			{
				return this._Heading1OL;
			}
			set
			{
				if ((this._Heading1OL != value))
				{
					this._Heading1OL = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Components")]
	public partial class Component
	{
		
		private int _CMPID;
		
		private string _Substance;
		
		private string _SDS_Name;
		
		private string _ListOfListsName;
		
		private string _Aliases;
		
		private bool _Proprietary;
		
		private string _CAS;
		
		private string _PEL;
		
		private string _ACGIH;
		
		private string _CERCLA_RQ;
		
		private string _SARA313;
		
		private string _SARA302TPQ;
		
		private string _SARA302RQ;
		
		private string _RCRACODE;
		
		private bool _IsProduct;
		
		private string _IARC;
		
		private string _NTP;
		
		private string _Note;
		
		public Component()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMPID", DbType="Int NOT NULL")]
		public int CMPID
		{
			get
			{
				return this._CMPID;
			}
			set
			{
				if ((this._CMPID != value))
				{
					this._CMPID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Substance", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Substance
		{
			get
			{
				return this._Substance;
			}
			set
			{
				if ((this._Substance != value))
				{
					this._Substance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDS_Name", DbType="NVarChar(255)")]
		public string SDS_Name
		{
			get
			{
				return this._SDS_Name;
			}
			set
			{
				if ((this._SDS_Name != value))
				{
					this._SDS_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListOfListsName", DbType="NVarChar(255)")]
		public string ListOfListsName
		{
			get
			{
				return this._ListOfListsName;
			}
			set
			{
				if ((this._ListOfListsName != value))
				{
					this._ListOfListsName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aliases", DbType="NVarChar(255)")]
		public string Aliases
		{
			get
			{
				return this._Aliases;
			}
			set
			{
				if ((this._Aliases != value))
				{
					this._Aliases = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proprietary", DbType="Bit NOT NULL")]
		public bool Proprietary
		{
			get
			{
				return this._Proprietary;
			}
			set
			{
				if ((this._Proprietary != value))
				{
					this._Proprietary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAS", DbType="NVarChar(255)")]
		public string CAS
		{
			get
			{
				return this._CAS;
			}
			set
			{
				if ((this._CAS != value))
				{
					this._CAS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PEL", DbType="NVarChar(255)")]
		public string PEL
		{
			get
			{
				return this._PEL;
			}
			set
			{
				if ((this._PEL != value))
				{
					this._PEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACGIH", DbType="NVarChar(255)")]
		public string ACGIH
		{
			get
			{
				return this._ACGIH;
			}
			set
			{
				if ((this._ACGIH != value))
				{
					this._ACGIH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CERCLA_RQ", DbType="NVarChar(255)")]
		public string CERCLA_RQ
		{
			get
			{
				return this._CERCLA_RQ;
			}
			set
			{
				if ((this._CERCLA_RQ != value))
				{
					this._CERCLA_RQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SARA313", DbType="NVarChar(255)")]
		public string SARA313
		{
			get
			{
				return this._SARA313;
			}
			set
			{
				if ((this._SARA313 != value))
				{
					this._SARA313 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SARA302TPQ", DbType="NVarChar(255)")]
		public string SARA302TPQ
		{
			get
			{
				return this._SARA302TPQ;
			}
			set
			{
				if ((this._SARA302TPQ != value))
				{
					this._SARA302TPQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SARA302RQ", DbType="NVarChar(255)")]
		public string SARA302RQ
		{
			get
			{
				return this._SARA302RQ;
			}
			set
			{
				if ((this._SARA302RQ != value))
				{
					this._SARA302RQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RCRACODE", DbType="NVarChar(255)")]
		public string RCRACODE
		{
			get
			{
				return this._RCRACODE;
			}
			set
			{
				if ((this._RCRACODE != value))
				{
					this._RCRACODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsProduct", DbType="Bit NOT NULL")]
		public bool IsProduct
		{
			get
			{
				return this._IsProduct;
			}
			set
			{
				if ((this._IsProduct != value))
				{
					this._IsProduct = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IARC", DbType="NVarChar(255)")]
		public string IARC
		{
			get
			{
				return this._IARC;
			}
			set
			{
				if ((this._IARC != value))
				{
					this._IARC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NTP", DbType="NVarChar(255)")]
		public string NTP
		{
			get
			{
				return this._NTP;
			}
			set
			{
				if ((this._NTP != value))
				{
					this._NTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(MAX)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this._Note = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
